### ISSUE TITLE
error when starting job with more than one argument in config

### ISSUE THREAD

**Issue by jphelton** [spark-jobserver/python-sjsclient#11]
job fails to created when the jobconfig parameter is a dict of more than one key value pair.

A look at the httprequest shows it's not sending serialized JSON but the older HTTP form post. key1=value1&key2=value2.  The error that comes back says something to the effect of "&" is a reserved keyword, are you sure it's placement here is correct.  If I take the config object and serialize it manually to a JSON string, then job will run properly

**Comment by noorul** [comment]
Are you creating a job or context? Which version of SJS are you using?

**Comment by noorul** [comment]
@jphelton Can you provide more information? See my question above.

**Comment by noorul** [comment]
@jphelton Let me know if you found a solution for your problem so that I can close this issue.

**Comment by noorul** [comment]
Closing this as I haven't got any response for long. You can re-open this later.
