### ISSUE TITLE
SJS Client returns 404 client error even when apps exist

### ISSUE THREAD

**Issue by Cyash** [spark-jobserver/python-sjsclient#26]
Hello guys I started using SJS client yesterday only to find it is broken whenever i try this simple
code 
`import time
import logging
import json
import sjsclient
from sjsclient import client

logging.basicConfig()
logger = logging.getLogger()
logger.setLevel(logging.INFO)

sjs = client.Client("http://ip.compute-1.amazonaws.com:8090")
for app in sjs.apps.list():
    print app.name`

it return this 404! I've double checked there are three apps currently exists under jars
sjsclient.exceptions.NotFoundException: NotFoundException: 404 Client Error: Not Found for url: http://ip.compute-1.amazonaws.com:8090/binaries, The requested resource could not be found.

although if I replace the above block of for loop with with this below code  it does lists all jobid's
` for job in sjs.jobs.list():
    print job.jobId`

I'm currently using jobserver 0.6.1, python2.7.13, any suggestions or fixes ?

**Comment by noorul** [comment]
You should use version 0.6.2

**Comment by noorul** [comment]
I mean version 0.6.2 of python-sjsclient

**Comment by Cyash** [comment]
then why does it say it supoorts 0.6.0+ in documentation? I mean please update that

**Comment by Cyash** [comment]
alright norul thanks ! I used pip install sjs-client to install this, what command do I have to use to install 0.6.2 client ? it will be really helpful, thanks!

**Comment by noorul** [comment]
pip install pyth in-state==0.6.2

**Comment by Cyash** [comment]
@noorul thank you very much!

**Comment by Cyash** [comment]
@noorul still shows the same error though

**Comment by noorul** [comment]
Can you paste entire eroor?

**Comment by Cyash** [comment]
sorry my bad, seems like it has got somethings from previous build, it works now you can close. but, thanks again!
