### ISSUE TITLE
404's on Job Creation

### ISSUE THREAD

**Issue by bitborn** [spark-jobserver/python-sjsclient#5]
I'm getting _occasional_ 404's when creating a job.

It appears `job_manager.create(...)` makes one request to create the job and then another request to get the job.

Job server will sometimes respond to the second request with a 404. This looks a lot like a race condition :crying_cat_face: 

Is there any way we could return a reference to the job on creation? This way the second request could be made lazily. Maybe we could add `sync` and `timeout` parameters to wait for the results? There might even be performance benefits to not making that second request.

I'd love to create a PR for this with a bit of direction.

**Comment by noorul** [comment]
Sorry for the delayed response. Please propose a patch.

**Comment by noorul** [comment]
Released a new version 0.1.2 with fix for this. Thank you for reporting and sorry for the delay.

**Comment by jomach** [comment]
This seems to break with 0.7.0 check my opened issue

**Comment by noorul** [comment]
@jomach python-sjsclient does not support 0.7.0. I will work on it.
