### ISSUE TITLE
api result issue

### ISSUE THREAD

**Issue by jomach** [spark-jobserver/python-sjsclient#8]
Hi, 

running the python-sjsclient  with version python-sjsclient==0.1.2 there is a bug on Job.py where when creating a Job the json field does not exist jet. This leads to KeyError.

   59         import ipdb
     60         ipdb.set_trace()
---> 61         result = {'status': resp['status']}
     62         result.update(resp['result'])
     63         return self._create_resource(result)

ipdb> resp
{u'status': u'STARTED', u'startTime': u'2016-09-28T10:54:50.255Z', u'classPath': u'com.here.JobServer.myclass', u'jobId': u'd254f451-e911-4d72-b580-60ded2603ba8', u'context': u'sql-context', u'duration': u'Job not done yet'}
ipdb> quit

**Comment by noorul** [comment]
which version of SJS are you using?

**Comment by noorul** [comment]
I think I need to add support for 0.7.0. See #9

**Comment by jomach** [comment]
ok the tests seem to be failing..

**Comment by jomach** [comment]
@noorul on the master.
